<?php

/**
 * Baseencargados
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $md_user_responsable_id
 * @property integer $md_user_enresponsabilidad_id
 * @property mdUser $mdUserResponsable
 * @property mdUser $mdUserEnresponsabilidad
 * 
 * @method integer    getMdUserResponsableId()          Returns the current record's "md_user_responsable_id" value
 * @method integer    getMdUserEnresponsabilidadId()    Returns the current record's "md_user_enresponsabilidad_id" value
 * @method mdUser     getMdUserResponsable()            Returns the current record's "mdUserResponsable" value
 * @method mdUser     getMdUserEnresponsabilidad()      Returns the current record's "mdUserEnresponsabilidad" value
 * @method encargados setMdUserResponsableId()          Sets the current record's "md_user_responsable_id" value
 * @method encargados setMdUserEnresponsabilidadId()    Sets the current record's "md_user_enresponsabilidad_id" value
 * @method encargados setMdUserResponsable()            Sets the current record's "mdUserResponsable" value
 * @method encargados setMdUserEnresponsabilidad()      Sets the current record's "mdUserEnresponsabilidad" value
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Baseencargados extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encargados');
        $this->hasColumn('md_user_responsable_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('md_user_enresponsabilidad_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdUser as mdUserResponsable', array(
             'local' => 'md_user_responsable_id',
             'foreign' => 'id'));

        $this->hasOne('mdUser as mdUserEnresponsabilidad', array(
             'local' => 'md_user_enresponsabilidad_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}