<?php

/**
 * Basepreparacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $materia_id
 * @property integer $docente_id
 * @property integer $evaluacion_id
 * @property timestamp $periodo
 * @property materia $materia
 * @property docente $docente
 * @property evaluacion $evaluacion
 * @property Doctrine_Collection $alumnoPreparacion
 * @property Doctrine_Collection $calendarioMaterias
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getMateriaId()          Returns the current record's "materia_id" value
 * @method integer             getDocenteId()          Returns the current record's "docente_id" value
 * @method integer             getEvaluacionId()       Returns the current record's "evaluacion_id" value
 * @method timestamp           getPeriodo()            Returns the current record's "periodo" value
 * @method materia             getMateria()            Returns the current record's "materia" value
 * @method docente             getDocente()            Returns the current record's "docente" value
 * @method evaluacion          getEvaluacion()         Returns the current record's "evaluacion" value
 * @method Doctrine_Collection getAlumnoPreparacion()  Returns the current record's "alumnoPreparacion" collection
 * @method Doctrine_Collection getCalendarioMaterias() Returns the current record's "calendarioMaterias" collection
 * @method preparacion         setId()                 Sets the current record's "id" value
 * @method preparacion         setMateriaId()          Sets the current record's "materia_id" value
 * @method preparacion         setDocenteId()          Sets the current record's "docente_id" value
 * @method preparacion         setEvaluacionId()       Sets the current record's "evaluacion_id" value
 * @method preparacion         setPeriodo()            Sets the current record's "periodo" value
 * @method preparacion         setMateria()            Sets the current record's "materia" value
 * @method preparacion         setDocente()            Sets the current record's "docente" value
 * @method preparacion         setEvaluacion()         Sets the current record's "evaluacion" value
 * @method preparacion         setAlumnoPreparacion()  Sets the current record's "alumnoPreparacion" collection
 * @method preparacion         setCalendarioMaterias() Sets the current record's "calendarioMaterias" collection
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Basepreparacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preparacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('materia_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('docente_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('evaluacion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('periodo', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('materia', array(
             'local' => 'materia_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('docente', array(
             'local' => 'docente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('evaluacion', array(
             'local' => 'evaluacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('alumnoPreparacion', array(
             'local' => 'id',
             'foreign' => 'preparacion_id'));

        $this->hasMany('calendarioMaterias', array(
             'local' => 'id',
             'foreign' => 'preparacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}