<?php

/**
 * Basemailing_alumnos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $alumno_id
 * @property integer $mailing_id
 * @property alumno $alumno
 * @property mailing $mailing
 * 
 * @method integer         getAlumnoId()   Returns the current record's "alumno_id" value
 * @method integer         getMailingId()  Returns the current record's "mailing_id" value
 * @method alumno          getAlumno()     Returns the current record's "alumno" value
 * @method mailing         getMailing()    Returns the current record's "mailing" value
 * @method mailing_alumnos setAlumnoId()   Sets the current record's "alumno_id" value
 * @method mailing_alumnos setMailingId()  Sets the current record's "mailing_id" value
 * @method mailing_alumnos setAlumno()     Sets the current record's "alumno" value
 * @method mailing_alumnos setMailing()    Sets the current record's "mailing" value
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Basemailing_alumnos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing_alumnos');
        $this->hasColumn('alumno_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('mailing_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('alumno', array(
             'local' => 'alumno_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('mailing', array(
             'local' => 'mailing_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}