<?php

/**
 * BasealumnoPreparacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $alumno_id
 * @property integer $preparacion_id
 * @property integer $forma_contacto_id
 * @property alumno $alumno
 * @property preparacion $preparacion
 * @property formaContacto $formaContacto
 * 
 * @method integer           getAlumnoId()          Returns the current record's "alumno_id" value
 * @method integer           getPreparacionId()     Returns the current record's "preparacion_id" value
 * @method integer           getFormaContactoId()   Returns the current record's "forma_contacto_id" value
 * @method alumno            getAlumno()            Returns the current record's "alumno" value
 * @method preparacion       getPreparacion()       Returns the current record's "preparacion" value
 * @method formaContacto     getFormaContacto()     Returns the current record's "formaContacto" value
 * @method alumnoPreparacion setAlumnoId()          Sets the current record's "alumno_id" value
 * @method alumnoPreparacion setPreparacionId()     Sets the current record's "preparacion_id" value
 * @method alumnoPreparacion setFormaContactoId()   Sets the current record's "forma_contacto_id" value
 * @method alumnoPreparacion setAlumno()            Sets the current record's "alumno" value
 * @method alumnoPreparacion setPreparacion()       Sets the current record's "preparacion" value
 * @method alumnoPreparacion setFormaContacto()     Sets the current record's "formaContacto" value
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasealumnoPreparacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno_preparacion');
        $this->hasColumn('alumno_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('preparacion_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('forma_contacto_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('alumno', array(
             'local' => 'alumno_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('preparacion', array(
             'local' => 'preparacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('formaContacto', array(
             'local' => 'forma_contacto_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}