<?php

/**
 * Basemailing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $texto
 * @property Doctrine_Collection $mailing_alumnos
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getTexto()           Returns the current record's "texto" value
 * @method Doctrine_Collection getMailingAlumnos()  Returns the current record's "mailing_alumnos" collection
 * @method mailing             setId()              Sets the current record's "id" value
 * @method mailing             setTexto()           Sets the current record's "texto" value
 * @method mailing             setMailingAlumnos()  Sets the current record's "mailing_alumnos" collection
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Basemailing extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('texto', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mailing_alumnos', array(
             'local' => 'id',
             'foreign' => 'mailing_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}