<?php

/**
 * Baseperiodo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $inicio
 * @property timestamp $fin
 * @property string $nombre
 * @property boolean $activo
 * @property Doctrine_Collection $preparacion
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method timestamp           getInicio()      Returns the current record's "inicio" value
 * @method timestamp           getFin()         Returns the current record's "fin" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method boolean             getActivo()      Returns the current record's "activo" value
 * @method Doctrine_Collection getPreparacion() Returns the current record's "preparacion" collection
 * @method periodo             setId()          Sets the current record's "id" value
 * @method periodo             setInicio()      Sets the current record's "inicio" value
 * @method periodo             setFin()         Sets the current record's "fin" value
 * @method periodo             setNombre()      Sets the current record's "nombre" value
 * @method periodo             setActivo()      Sets the current record's "activo" value
 * @method periodo             setPreparacion() Sets the current record's "preparacion" collection
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Baseperiodo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('periodo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('inicio', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('fin', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('preparacion', array(
             'local' => 'id',
             'foreign' => 'periodo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}