<?php

/**
 * Basemateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $facultad_id
 * @property facultad $facultad
 * @property Doctrine_Collection $preparacion
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method integer             getFacultadId()  Returns the current record's "facultad_id" value
 * @method facultad            getFacultad()    Returns the current record's "facultad" value
 * @method Doctrine_Collection getPreparacion() Returns the current record's "preparacion" collection
 * @method materia             setId()          Sets the current record's "id" value
 * @method materia             setNombre()      Sets the current record's "nombre" value
 * @method materia             setFacultadId()  Sets the current record's "facultad_id" value
 * @method materia             setFacultad()    Sets the current record's "facultad" value
 * @method materia             setPreparacion() Sets the current record's "preparacion" collection
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Basemateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('facultad_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('facultad', array(
             'local' => 'facultad_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('preparacion', array(
             'local' => 'id',
             'foreign' => 'materia_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}