<?php

/**
 * BasehorarioEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $alumno_id
 * @property integer $horario_id
 * @property alumno $alumno
 * @property calendarioMaterias $calendarioMaterias
 * 
 * @method integer            getAlumnoId()           Returns the current record's "alumno_id" value
 * @method integer            getHorarioId()          Returns the current record's "horario_id" value
 * @method alumno             getAlumno()             Returns the current record's "alumno" value
 * @method calendarioMaterias getCalendarioMaterias() Returns the current record's "calendarioMaterias" value
 * @method horarioEstudiante  setAlumnoId()           Sets the current record's "alumno_id" value
 * @method horarioEstudiante  setHorarioId()          Sets the current record's "horario_id" value
 * @method horarioEstudiante  setAlumno()             Sets the current record's "alumno" value
 * @method horarioEstudiante  setCalendarioMaterias() Sets the current record's "calendarioMaterias" value
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasehorarioEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('horario_estudiante');
        $this->hasColumn('alumno_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('horario_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('alumno', array(
             'local' => 'alumno_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('calendarioMaterias', array(
             'local' => 'horario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}