<?php

/**
 * BasemdPassportGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $md_passport_id
 * @property integer $md_group_id
 * @property mdPassport $mdPassport
 * @property mdGroup $mdGroup
 * 
 * @method integer         getMdPassportId()   Returns the current record's "md_passport_id" value
 * @method integer         getMdGroupId()      Returns the current record's "md_group_id" value
 * @method mdPassport      getMdPassport()     Returns the current record's "mdPassport" value
 * @method mdGroup         getMdGroup()        Returns the current record's "mdGroup" value
 * @method mdPassportGroup setMdPassportId()   Sets the current record's "md_passport_id" value
 * @method mdPassportGroup setMdGroupId()      Sets the current record's "md_group_id" value
 * @method mdPassportGroup setMdPassport()     Sets the current record's "mdPassport" value
 * @method mdPassportGroup setMdGroup()        Sets the current record's "mdGroup" value
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdPassportGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_passport_group');
        $this->hasColumn('md_passport_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_group_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdPassport', array(
             'local' => 'md_passport_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('mdGroup', array(
             'local' => 'md_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}