<?php

/**
 * BasemdPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $mdGroupPermission
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method Doctrine_Collection getGroups()            Returns the current record's "Groups" collection
 * @method Doctrine_Collection getMdGroupPermission() Returns the current record's "mdGroupPermission" collection
 * @method mdPermission        setId()                Sets the current record's "id" value
 * @method mdPermission        setName()              Sets the current record's "name" value
 * @method mdPermission        setDescription()       Sets the current record's "description" value
 * @method mdPermission        setGroups()            Sets the current record's "Groups" collection
 * @method mdPermission        setMdGroupPermission() Sets the current record's "mdGroupPermission" collection
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasemdPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_permission');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mdGroup as Groups', array(
             'refClass' => 'mdGroupPermission',
             'local' => 'permission_id',
             'foreign' => 'group_id'));

        $this->hasMany('mdGroupPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}