<?php

/**
 * Baseevaluacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $preparacion
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method Doctrine_Collection getPreparacion() Returns the current record's "preparacion" collection
 * @method evaluacion          setId()          Sets the current record's "id" value
 * @method evaluacion          setNombre()      Sets the current record's "nombre" value
 * @method evaluacion          setPreparacion() Sets the current record's "preparacion" collection
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Baseevaluacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evaluacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('preparacion', array(
             'local' => 'id',
             'foreign' => 'evaluacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}