# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            9bb8e507bd2a97bc683b9b761d70f4aa6e7f3b79

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    #Culture
    i18n:                   on
    default_culture:        es

    standard_helpers: [Partial, Cache, I18N, Date]

    # Enable de login by Mastodonte Auth
    login_module:           mdAuth
    login_action:           signin
    secure_module:          mdAuth
    secure_action:          secure

    #Modules enabled
    enabled_modules:        [ mdAuth, mdWebImage]