<?php

/**
 * calendarioMaterias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class calendarioMaterias extends BasecalendarioMaterias
{
  public static $days = array(
              0 => 'lunes',
              1 => 'martes',
              2 => 'miercoles',
              3 => 'jueves',
              4 => 'viernes',
              5 => 'sabado',
             );
             
  public static $hours = array(
              7 => '07',
              8 => '08',
              9 => '09',
              10 => '10',
              11 => '11',
              12 => '12',
              13 => '13',
              14 => '14',
              15 => '15',
              16 => '16',
              17 => '17',
              18 => '18',
              19 => '19',
              20 => '20',
              21 => '21',
              22 => '22',
              23 => '23',
             );
  public static $minutes = array(
              0 => '00',
              15 => '15',
              30 => '30',
              45 => '45',
             );
             
  public function getFormattedTime(){
		$hour = 0;
		if(($this->getHour() / 10 ) < 1){
			$hour = "0".$this->getHour();
		} else{
			$hour = $this->getHour();
		}
		$minutes = $this->getMinutes();
		if($minutes == 0){
			$minutes = "0".$minutes;
		}
    return $this->getDay()."_".$hour."_".$minutes;
  }
  
  public function calculatedFinishTime(){
    $minutes = $this->getMinutes() + $this->getDuration();
    $return = $this->getDay()."_".($this->getHour() + floor($minutes/60))."_".($minutes%60);
    return $return;
  }
}
