<?php

/**
 * materia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class materia extends Basemateria
{
  public function __toString(){
    return $this->getNombre();
  }

  public static function retrieveMateria($id)
  {
      return Doctrine::getTable("materia")->find($id);
  }
}
