<?php

/**
 * preparacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class preparacion extends Basepreparacion
{
	public function __toString(){
		$period = $this->calculatePeriodo();
		return $period.' - '.$this->getDocente()->getNombre().' - '.$this->getMateria()->getNombre();
	}
	
	public function calculatePeriodo(){
		return date('m / Y',mdBasicFunction::convert_datetime($this->getPeriodo()));
	}
}
