<?php

/**
 * preparacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    instituto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class preparacion extends Basepreparacion {

    public function __toString() {
        $period = $this->calculatePeriodo();
        return $period . ' - ' . $this->getDocente()->getNombre() . ' - ' . $this->getMateria()->getNombre();
    }

    public function calculatePeriodo() {
        return date('m / Y', mdBasicFunction::convert_datetime($this->getPeriodo()));
    }

    public function retrieveStartHourTime() {
        $hours = explode(":", $this->getHoraInicio());
        return $hours[0] . ":" . $hours[1];
    }

    public function retrieveFinishHourTime() {
        $hours = explode(":", $this->getHoraFin());
        return $hours[0] . ":" . $hours[1];
    }

    private $globalPaymentStatus = NULL;
    
    private function retrieveLocalGlobalPaymentStatus()
    {
      if(is_null($this->globalPaymentStatus))
      {
        $this->globalPaymentStatus = alumnoPreparacionTable::retrieveAllPaymentsOfPreparation($this->getId());
      }
      return $this->globalPaymentStatus;
    }
    
    public function retrieveGlobalPaymentStatus() {
        $results = $this->retrieveLocalGlobalPaymentStatus();
        $salida = array();
        $hasRows = false;
        $pago = 0;
        $pagoCompleto = 0;
        $total = 0;
        foreach($results as $row)
        {
            $pago += (integer) $row['pago'];
            $pagoCompleto += (integer) $row['pago_completo'];
            $total++; 
            $hasRows = true;
        }
        if(!$hasRows || $pagoCompleto == $total) return "green";
        if($pagoCompleto == 0 && $pago == 0)
        {
          return "red";
        }
        return "yellow";
    }

}
