all:
  .tiny:
    #jfilebrowser_path: "/tiny"

  .plugins:
########Usuarios########
# Activar los atributos para los usuarios
    plugins_user_attributes: true
# Activar la media para el usuario
    plugins_user_media: true
# Activar la carga de grupos y permisos para el usuario.
    plugins_user_groups_permissions: true
# Desactivar el envio de mails por testeo
    plugins_user_not_send_mail: false

#########Noticias########
# Activar que una noticia sea destacada
    plugins_news_feature: false
# Activar la media para las noticias
    plugins_news_media: false
# Activar las categorias para las noticias
    plugins_news_category: false
# Activar los comentarios para las noticias
    plugins_news_commentary: false
# Activar los ratings para las noticias
    plugins_news_ratings: false

#########Categorias########
# Para habilitar la media de las categorias
    plugins_category_media: false
# Para habilitar los atributos de las categorias
    plugins_category_attributes: false
# Para habilitar el widget de color picker en las categorias
    plugins_category_attribute_color_picker: false

#########Dynamic Content########
# Activar la media para los dynamic content
    plugins_dynamic_media: false
# Activar las categorias para los dynamic content
    plugins_dynamic_category: false
# Activar las opciones de fecha para los dynamic content
    plugins_dynamic_show_publish_at: false
# Activar manejo de tipos de dynamicContent por separado
    plugins_dynamic_manage: false
# Activar el manejo de prioridades
    plugins_dynamic_priority: false

# Activa la separacion de los menues del backend por las categorias que contienen los productos.
    plugins_products_manage: false
# Selecciona que moneda va a usar por defecto.
    plugins_products_default_currency: 1

#########Uploader de imagenes#######
# Por defecto se podran subir solo imagenes y el javascript que dibuja las cosas vendra
# sin que se le pueda poner comentarios.
# Los parametros para modificar este comportamiento son. plugins_upload_content_type_ + clase del objeto
#
# ejemplo para el mdNews para que acepte archivos .pdf se pondria.
# plugins_upload_content_type_mdNews: '*.jpg;*.jpeg;*.gif;*.png;*.doc;*.pdf'

    plugins_upload_content_type_mdDynamicContent: '*.jpg;*.jpeg;*.gif;*.png;*.doc;*.pdf'

#########Archivos de configuracion de xml###############
    plugins_mdAuthFile_xml_edit: false
    plugins_mdBackendGroupsFile_xml_edit: true

######### Features ###################
# Activar la creacion de features
    plugins_feature_create: false

######### Ratings ####################
# Activar el poder votar dos veces
    plugins_mdRating_multi_vote: false

######### Atributos ##################
# Setea el widget de años con el mayor rango posible
    plugins_datepicker_big_year: false

######### MdFileHandler ###############
# Setea si obtiene las imagenes por fecha ascendente o descendente
    image_order_ascending: false

######### Images Resolution #################
    image_cuality_change: false
    image_cuality_porcent: 75

######### ImageMagick Commands Debug ###############
    plugin_mdMedia_imagick_debug: false

###########Shopping##########
    plugins_shopping_attribute: false
    plugins_shopping_feature: false
    plugins_shopping_media: false
    plugins_shopping_category: false


###########Geo IP ###########
    plugins_user_geoip: false

########## MdImageFileGallerie ###########
# Formatos soportados
    plugins_upload_content_type_categories: '*.jpg;*.jpeg;*.gif;*.png;*.pdf'

########## MdUserMessages ################
#Forma en que se muestra los usuarios. (Por mail, por usuario o por nombre y apellido)
#Esto estan por orden de prioridad o sea el primero que este en true va a ser el que se muestre.
    plugins_user_message_show_mail: false
    plugins_user_message_show_username: false
    plugins_user_message_show_user: false
    plugins_user_message_media: false

########## MdUserStatus #################
    plugins_user_status_active: false

########## mdWall #################

    plugins_wall_commentable: false
    plugins_wall_media: false
